version: '3.9'

services:
  nestjs-example:
    container_name: nestjs-example
    image: nestjs-example:1.0.0
    build: .
    ports:
      - 3000:3000
    env_file:
      - ./.env
    depends_on:
      - db
  
  db:
    container_name: db
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - ./.docker/data/postgres:/var/lib/postgresql/data
    
volumes:
  pgdata: {}
